# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dmf-device-ui
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

requirements:
  build:
    #: .. versionadded:: 0.10
    - debounce
    #: .. versionadded:: 0.13
    #:     Add logging specific to method context.
    - logging-helpers >=0.4
    - microdrop >=2.0.post22.dev158803465
    - microdrop-utility >=0.4
    - networkx >=1.10
    - opencv-helpers >=0.1.post1
    - pandas >=0.17.0
    - path_helpers >=0.2
    - paver
    - pygst_utils >=0.3.post12
    - svg-model >=0.6
    #: ..versionchanged:: 0.7
    #: ..versionchanged:: 0.11.2
    - wheeler.pygtkhelpers >=0.21.1
    #: ..versionchanged:: 0.6.2
    - zmq-plugin >=0.3

  run:
    #: .. versionadded:: 0.10
    - debounce
    #: .. versionadded:: 0.13
    #:     Add logging specific to method context.
    - logging-helpers >=0.4
    - microdrop >=2.0.post22.dev158803465
    - microdrop-utility >=0.4
    - networkx >=1.10
    - opencv-helpers >=0.1.post1
    - pandas >=0.17.0
    - path_helpers >=0.2
    - pygst_utils >=0.3.post12
    - svg-model >=0.6
    #: ..versionchanged:: 0.7
    #: ..versionchanged:: 0.11.2
    - wheeler.pygtkhelpers >=0.21.1
    #: ..versionchanged:: 0.6.2
    - zmq-plugin >=0.3

#: .. versionadded:: 0.10
test:
  imports:
    - dmf_device_ui
    - dmf_device_ui.bin
    - dmf_device_ui.bin.device_view
    - dmf_device_ui.canvas
    - dmf_device_ui.client
    - dmf_device_ui.notifier
    - dmf_device_ui.plugin
    - dmf_device_ui.view

about:
  #: .. versionchanged:: 0.10
  home: http://github.com/sci-bots/{{ PKG_NAME }}
  #: .. versionchanged:: 0.10
  license: BSD-3
