# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dmf-device-ui
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

requirements:
  build:
    - microdrop >=2.0.post22.dev158803465
    - microdrop-utility >=0.4
    - networkx >=1.10
    - opencv-helpers >=0.1.post1
    - pandas >=0.17.0
    - path_helpers >=0.2
    - paver
    - pygst_utils >=0.3.post12
    - svg-model >=0.6
    #: ..versionchanged:: 0.7
    - wheeler.pygtkhelpers >=0.20
    #: ..versionchanged:: 0.6.2
    - zmq-plugin >=0.3

  run:
    - microdrop >=2.0.post22.dev158803465
    - microdrop-utility >=0.4
    - networkx >=1.10
    - opencv-helpers >=0.1.post1
    - pandas >=0.17.0
    - path_helpers >=0.2
    - pygst_utils >=0.3.post12
    - svg-model >=0.6
    #: ..versionchanged:: 0.7
    - wheeler.pygtkhelpers >=0.20
    #: ..versionchanged:: 0.6.2
    - zmq-plugin >=0.3

about:
  home: http://github.com/wheeler-microfluidics/{{ PKG_NAME }}
  #: .. versionchanged:: X.X.X
  license: BSD-3
